//go:build linux

package sandbox

import (
	"fmt"
	"maps"
	"runtime"
	"slices"
	"strconv"
	"strings"
	"unsafe"

	"golang.org/x/sys/unix"
)

// The workload's syscall filter: a pure-Go classic-BPF program installed with
// prctl(PR_SET_SECCOMP) — no libseccomp/cgo. It is a DENYLIST: syscalls are allowed by default
// and a small set of kernel-attack-surface expanders is refused with EPERM (the action Docker's
// default profile uses, so a workload degrades gracefully instead of dying on SIGSYS).
//
// It is what keeps the read-only root read-only. Everything else here runs the workload with an
// emptied capability bounding set and a non-root id, but nothing in that stops it from calling
// unshare(CLONE_NEWUSER) and holding a full namespaced capability set in a namespace of its own —
// and with CAP_SYS_ADMIN there, mounting a writable tmpfs over any path in the tree. Denying the
// namespace and mount syscalls is what closes that door.
//
// seccompProgram builds the filter and installSeccomp is the only thing that touches the kernel,
// so the whole denylist is decided in code the tests drive directly — an arch table that silently
// stopped filtering is precisely the failure they exist to catch.

type sockFilter struct {
	code uint16
	jt   uint8
	jf   uint8
	k    uint32
}

const (
	// classic-BPF opcodes
	bpfLdWAbs = 0x20 // BPF_LD  | BPF_W   | BPF_ABS
	bpfJeqK   = 0x15 // BPF_JMP | BPF_JEQ | BPF_K
	bpfJgeK   = 0x35 // BPF_JMP | BPF_JGE | BPF_K
	bpfJsetK  = 0x45 // BPF_JMP | BPF_JSET| BPF_K
	bpfRetK   = 0x06 // BPF_RET | BPF_K

	// struct seccomp_data field offsets
	offNr    = 0
	offArch  = 4
	offArgs0 = 16 // args[0]; little-endian, so the low 32 bits sit here

	seccompRetAllow = 0x7fff0000
	seccompRetErrno = 0x00050000 // | errno

	// Linux errno values, spelled out rather than taken from the host's syscall package: the
	// program is compiled for the workload's kernel, not for the machine building it.
	errnoEPERM  = 1
	errnoENOSYS = 38

	// x32SyscallBit marks the x32 ABI on x86_64; the ceiling check denies it along with every
	// other out-of-table number, and the constant remains because the tests name it.
	// seccomp_data.arch still reads AUDIT_ARCH_X86_64
	// for an x32 process, so without this every bare syscall-number comparison below simply
	// misses and the call is allowed.
	x32SyscallBit = 0x40000000

	// cloneNewNamespaces are the CLONE_NEW* flags. clone(2) cannot be denied outright — the Go
	// runtime and every threading libc create threads with it — so it is allowed unless it asks
	// for a new namespace, which is the nested-user-namespace primitive unshare is denied for.
	cloneNewNamespaces = 0x00020000 | // CLONE_NEWNS   (NOT 0x100 — that is CLONE_VM, which every
		//                                thread creation sets; masking on it would deny them all)
		0x02000000 | // CLONE_NEWCGROUP
		0x04000000 | // CLONE_NEWUTS
		0x08000000 | // CLONE_NEWIPC
		0x10000000 | // CLONE_NEWUSER
		0x20000000 | // CLONE_NEWPID
		0x40000000 // CLONE_NEWNET
)

// archFilter is one architecture's filter inputs: the AUDIT_ARCH value seccomp reports, the
// syscall numbers for that ABI and the name table a custom policy is resolved against. Numbers
// are per-architecture, which is why a table exists at all.
type archFilter struct {
	auditArch uint32
	clone     uint32
	clone3    uint32
	denied    []uint32
	// names is this ABI's syscall name table (syscalls.go, generated by hack/gensyscalls from
	// x/sys/unix). It exists so a custom policy can name a syscall rather than number it —
	// numbers differ per ABI, and a policy that silently denied the wrong call on one
	// architecture is the failure this avoids.
	names map[string]uint32
	// maxNr is the highest syscall number the table knows. Everything above it is denied: a
	// denylist is open at the top by nature, and a syscall the kernel grew after this table was
	// generated is exactly the one nobody has decided about yet.
	maxNr uint32
}

// archFilters maps GOARCH to its filter. An architecture absent from this table gets NO filter,
// which is why installSeccomp refuses to run there rather than proceeding unprotected.
var archFilters = map[string]archFilter{
	"amd64": {
		auditArch: 0xC000003E, // AUDIT_ARCH_X86_64
		clone:     56,
		clone3:    435,
		names:     syscallsAMD64,
		maxNr:     syscallsAMD64Max,
		denied: []uint32{
			101, // ptrace
			103, // syslog
			135, // personality
			153, // vhangup
			155, // pivot_root
			161, // chroot
			163, // acct
			164, // settimeofday
			165, // mount
			166, // umount2
			167, // swapon
			168, // swapoff
			169, // reboot
			170, // sethostname
			171, // setdomainname
			172, // iopl
			173, // ioperm
			175, // init_module
			176, // delete_module
			179, // quotactl
			212, // lookup_dcookie
			227, // clock_settime
			237, // mbind
			238, // set_mempolicy
			239, // get_mempolicy
			246, // kexec_load
			248, // add_key
			249, // request_key
			250, // keyctl
			272, // unshare
			279, // move_pages
			298, // perf_event_open
			300, // fanotify_init
			304, // open_by_handle_at
			308, // setns
			310, // process_vm_readv
			311, // process_vm_writev
			312, // kcmp
			313, // finit_module
			320, // kexec_file_load
			321, // bpf
			323, // userfaultfd
			425, // io_uring_setup
			426, // io_uring_enter
			427, // io_uring_register
			428, // open_tree
			429, // move_mount
			430, // fsopen
			431, // fsconfig
			432, // fsmount
			433, // fspick
			438, // pidfd_getfd
			440, // process_madvise
			442, // mount_setattr
			443, // quotactl_fd
			450, // set_mempolicy_home_node
		},
	},
	"arm64": {
		auditArch: 0xC00000B7, // AUDIT_ARCH_AARCH64
		clone:     220,
		clone3:    435,
		names:     syscallsARM64,
		maxNr:     syscallsARM64Max,
		// The asm-generic numbering. iopl/ioperm do not exist on this architecture.
		denied: []uint32{
			18,  // lookup_dcookie
			39,  // umount2
			40,  // mount
			41,  // pivot_root
			51,  // chroot
			58,  // vhangup
			60,  // quotactl
			89,  // acct
			92,  // personality
			97,  // unshare
			104, // kexec_load
			105, // init_module
			106, // delete_module
			112, // clock_settime
			116, // syslog
			117, // ptrace
			142, // reboot
			161, // sethostname
			162, // setdomainname
			170, // settimeofday
			217, // add_key
			218, // request_key
			219, // keyctl
			224, // swapon
			225, // swapoff
			235, // mbind
			236, // get_mempolicy
			237, // set_mempolicy
			239, // move_pages
			241, // perf_event_open
			262, // fanotify_init
			265, // open_by_handle_at
			268, // setns
			270, // process_vm_readv
			271, // process_vm_writev
			272, // kcmp
			273, // finit_module
			280, // bpf
			282, // userfaultfd
			294, // kexec_file_load
			425, // io_uring_setup
			426, // io_uring_enter
			427, // io_uring_register
			428, // open_tree
			429, // move_mount
			430, // fsopen
			431, // fsconfig
			432, // fsmount
			433, // fspick
			438, // pidfd_getfd
			440, // process_madvise
			442, // mount_setattr
			443, // quotactl_fd
			450, // set_mempolicy_home_node
		},
	},
}

// seccompProgram assembles the BPF filter for goarch. It returns an error for an architecture
// with no table: an unfiltered workload must be a refusal to start, never a silent downgrade.
//
// The layout, and why each branch exists:
//
//	ld arch;  arch != native            -> DENY   (a foreign ABI has different numbers, so the
//	                                               comparisons below would be meaningless)
//	ld nr;    nr > maxNr                -> DENY   (a syscall this build never heard of — one the
//	                                               kernel grew later, or an x32 call, which keeps
//	                                               AUDIT_ARCH_X86_64 and ORs 0x40000000 into the
//	                                               number, landing far above any real one)
//	          nr == clone              -> flags check
//	          nr == clone3             -> ENOSYS  (its flags live behind a pointer seccomp cannot
//	                                               read; ENOSYS makes libc fall back to clone,
//	                                               which IS filtered)
//	          nr in denied             -> DENY
//	                                     -> ALLOW
func seccompProgram(goarch string, policy *SeccompPolicy) ([]sockFilter, error) {
	a, ok := archFilters[goarch]
	if !ok {
		return nil, fmt.Errorf("seccomp: no syscall filter for GOARCH %q", goarch)
	}
	denied, err := applyPolicy(policy, a)
	if err != nil {
		return nil, err
	}
	a.denied = denied

	var f []sockFilter
	stmt := func(code uint16, k uint32) { f = append(f, sockFilter{code: code, k: k}) }
	jmp := func(code uint16, k uint32) int { f = append(f, sockFilter{code: code, k: k}); return len(f) - 1 }

	stmt(bpfLdWAbs, offArch)
	archIdx := jmp(bpfJeqK, a.auditArch) // == native falls through; != jumps to deny
	stmt(bpfLdWAbs, offNr)
	// The ceiling closes the denylist at the top, which is the one thing a denylist cannot do by
	// itself: everything above the highest number this build knows is refused, so a syscall added
	// by a later kernel is denied until the table is regenerated and someone decides about it.
	// It subsumes the x32 check — 0x40000000 is far above any real syscall number.
	ceilIdx := jmp(bpfJgeK, a.maxNr+1)
	cloneIdx := jmp(bpfJeqK, a.clone)
	clone3Idx := jmp(bpfJeqK, a.clone3)
	deniedIdx := make([]int, 0, len(a.denied))
	for _, nr := range a.denied {
		deniedIdx = append(deniedIdx, jmp(bpfJeqK, nr))
	}

	stmt(bpfRetK, seccompRetAllow) // the fallthrough for everything not named above
	denyIdx := len(f)
	stmt(bpfRetK, seccompRetErrno|errnoEPERM)
	enosysIdx := len(f)
	stmt(bpfRetK, seccompRetErrno|errnoENOSYS)

	// clone: allow unless it requests a new namespace.
	cloneCheckIdx := len(f)
	stmt(bpfLdWAbs, offArgs0)
	cloneFlagIdx := jmp(bpfJsetK, cloneNewNamespaces)
	stmt(bpfRetK, seccompRetAllow)
	cloneDenyIdx := len(f)
	stmt(bpfRetK, seccompRetErrno|errnoEPERM)

	// Classic BPF jumps are forward-only 8-bit offsets, which is why every target sits after
	// every jump that reaches it.
	f[archIdx].jf = jumpTo(archIdx, denyIdx)
	f[ceilIdx].jt = jumpTo(ceilIdx, denyIdx)
	f[cloneIdx].jt = jumpTo(cloneIdx, cloneCheckIdx)
	f[clone3Idx].jt = jumpTo(clone3Idx, enosysIdx)
	for _, i := range deniedIdx {
		f[i].jt = jumpTo(i, denyIdx)
	}
	f[cloneFlagIdx].jt = jumpTo(cloneFlagIdx, cloneDenyIdx)
	return f, nil
}

// maxDenied is how many syscalls the denylist can hold. Classic-BPF jumps carry an 8-bit
// displacement, and the longest one here — the arch mismatch at instruction 1 jumping to the
// deny return past every syscall comparison — is 5 + len(denied). A policy that overran it
// would truncate a jump into the middle of the program, so it is refused instead.
const maxDenied = 250

// applyPolicy returns the architecture's denylist with the policy's Deny added and its Allow
// removed. A nil policy returns the built-in list unchanged.
//
// A function rather than a method because SeccompPolicy is the CONTRACT's type (api/sandbox), and
// Go will not let this package hang behaviour off a type it does not own — which is the rule
// working as intended: what a policy MEANS belongs to whoever installs the filter.
func applyPolicy(p *SeccompPolicy, a archFilter) ([]uint32, error) {
	if p == nil || (len(p.Deny) == 0 && len(p.Allow) == 0) {
		return a.denied, nil
	}

	denied := make(map[uint32]struct{}, len(a.denied)+len(p.Deny))
	for _, nr := range a.denied {
		denied[nr] = struct{}{}
	}
	for _, name := range p.Deny {
		nr, err := a.syscallNumber(name)
		if err != nil {
			return nil, err
		}
		denied[nr] = struct{}{}
	}
	// Allow runs last, so a syscall named in both is allowed — the explicit escape hatch wins
	// over the default it was written to override.
	for _, name := range p.Allow {
		nr, err := a.syscallNumber(name)
		if err != nil {
			return nil, err
		}
		delete(denied, nr)
	}

	if len(denied) > maxDenied {
		return nil, fmt.Errorf("seccomp: %d denied syscalls exceeds the %d a classic-BPF jump can reach",
			len(denied), maxDenied)
	}
	return slices.Sorted(maps.Keys(denied)), nil
}

// syscallNumber resolves a policy entry — a syscall name ("io_uring_setup") or a decimal number
// — to this architecture's syscall number. clone and clone3 are refused: they are structural
// branches of the filter, not denylist entries, and naming one would add a comparison the
// branch above it already shadows.
func (a archFilter) syscallNumber(entry string) (uint32, error) {
	name := strings.TrimSpace(entry)
	if name == "" {
		return 0, fmt.Errorf("seccomp: empty syscall name in policy")
	}
	if name == "clone" || name == "clone3" {
		return 0, fmt.Errorf("seccomp: %s is filtered by its flags, not by name; it cannot appear in a policy", name)
	}
	if nr, err := strconv.ParseUint(name, 10, 32); err == nil {
		return uint32(nr), nil
	}
	if nr, ok := a.names[name]; ok {
		return nr, nil
	}
	return 0, fmt.Errorf("seccomp: unknown syscall %q (not in this architecture's table)", name)
}

// jumpTo is the classic-BPF displacement from the instruction at from to the one at to. It panics
// on a backward or out-of-range jump: both are programming errors in the layout above, and a
// silently truncated offset would produce a filter that allows what it claims to deny.
func jumpTo(from, to int) uint8 {
	d := to - from - 1
	if d < 0 || d > 255 {
		panic(fmt.Sprintf("seccomp: jump from %d to %d is out of range", from, to))
	}
	return uint8(d)
}

type sockFprog struct {
	length uint16
	_      [6]byte // pad so filter is 8-byte aligned, matching C struct sock_fprog on 64-bit
	filter *sockFilter
}

// installSeccomp applies the filter to the calling thread and every descendant. It requires
// PR_SET_NO_NEW_PRIVS to have been set first (dropPrivileges does that before calling this), and
// the caller must already be pinned to its OS thread — the filter lands on this thread, and the
// execve that hands control to the workload has to happen on the same one.
//
// It FAILS CLOSED on an architecture with no filter table: dropPrivileges propagates the error
// and the sandbox refuses to exec the workload. Returning nil there would leave a workload
// running with no syscall filter at all while every layer above reported success — a build for
// an unlisted GOARCH is a reason to add a table, not to run unprotected.
func installSeccomp(policy *SeccompPolicy) error {
	prog, err := seccompProgram(runtime.GOARCH, policy)
	if err != nil {
		return err
	}
	fprog := sockFprog{length: uint16(len(prog)), filter: &prog[0]}
	_, _, errno := unix.Syscall(unix.SYS_PRCTL, unix.PR_SET_SECCOMP, unix.SECCOMP_MODE_FILTER,
		uintptr(unsafe.Pointer(&fprog)))
	runtime.KeepAlive(prog)
	if errno != 0 {
		return fmt.Errorf("prctl(SET_SECCOMP): %w", errno)
	}
	return nil
}
