// Command gencomments renders the doc comments of the API types into a compiled map, so the
// schemas the server publishes carry the same descriptions the types carry — that is what
// `kubectl explain` prints.
//
// It exists because the extraction needs the SOURCE: invopop's AddGoComments parses the .go
// files with go/parser, and a deployed binary has none. So the parse happens once, here, at
// build time (`make comments`), and its result is compiled in.
//
// It reads this module only. The Kubernetes types these objects embed document themselves at
// run time — apimachinery ships SwaggerDoc() for them, which is the text Kubernetes publishes
// for its own API — so there is nothing to extract for those and no second rendering of them.
//
// Run from the api module root: go run ./internal/gencomments
package main

import (
	"flag"
	"fmt"
	"go/format"
	"log"
	"maps"
	"os"
	"regexp"
	"slices"
	"strings"

	genschema "github.com/invopop/jsonschema"
)

// basePkg is the import path the walked directories are relative to. It must match the types'
// own PkgPath, since that is the key the reflector looks a comment up by.
const basePkg = "github.com/ks-tool/horchestra/api"

// out is where the map is written; the staleness test overrides it to render into a temp file
// and compare, which is the only way to check the committed file against the current source.
var out = flag.String("o", "scheme/comments_gen.go", "file to write the generated map to")

func main() {
	flag.Parse()
	comments := ownComments()

	var b strings.Builder
	b.WriteString("// Code generated by internal/gencomments; DO NOT EDIT.\n")
	b.WriteString("// Regenerate with `make comments` after changing a doc comment on an API type.\n\n")
	b.WriteString("package scheme\n\n")
	b.WriteString("// goComments maps a fully qualified type or field to its Go doc comment. The reflector\n")
	b.WriteString("// reads it to fill each schema's description, which is what a client shows when asked to\n")
	b.WriteString("// explain a field.\n")
	b.WriteString("var goComments = map[string]string{\n")
	for _, k := range slices.Sorted(maps.Keys(comments)) {
		fmt.Fprintf(&b, "\t%q: %q,\n", k, comments[k])
	}
	b.WriteString("}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		log.Fatalf("format %s: %v", *out, err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatalf("write %s: %v", *out, err)
	}
	log.Printf("wrote %s (%d entries)", *out, len(comments))
}

// ownComments extracts this module's API-group packages, walking from the module root so the
// keys the walk builds are the packages' real import paths.
func ownComments() map[string]string {
	r := new(genschema.Reflector)
	// WithFullComment keeps a type's whole doc comment rather than its first sentence: these
	// comments carry the reasoning an operator needs, and truncating them at the first period
	// would publish the least useful half.
	if err := r.AddGoComments(basePkg, ".", genschema.WithFullComment()); err != nil {
		log.Fatalf("extract comments: %v", err)
	}
	return collect(r.CommentMap, isKindPackage)
}

// collect keeps the comments whose key passes want, with the source's line wrapping undone.
func collect(in map[string]string, want func(string) bool) map[string]string {
	out := make(map[string]string, len(in))
	for k, v := range in {
		if c := strings.TrimSpace(v); c != "" && want(k) {
			out[k] = unwrap(c)
		}
	}
	return out
}

// unwrap undoes the source's own line wrapping. A doc comment is hard-wrapped to the file's
// column limit, and those newlines are not part of the text — published verbatim they collide
// with the reader's own wrapping and come out as a staircase. A single newline therefore becomes
// a space, a blank line stays a paragraph break, and a line that begins a list item or is
// indented (a list continuation, a code block) is left on its own line, since its shape IS the
// content.
func unwrap(text string) string {
	paras := strings.Split(text, "\n\n")
	for i, para := range paras {
		var b strings.Builder
		for _, line := range strings.Split(para, "\n") {
			switch {
			case b.Len() == 0:
			case standalone(line):
				b.WriteByte('\n')
			default:
				b.WriteByte(' ')
			}
			b.WriteString(strings.TrimRight(line, " \t"))
		}
		paras[i] = b.String()
	}
	return strings.Join(paras, "\n\n")
}

// standalone reports whether a line must keep its own break: a list item, or indented text.
func standalone(line string) bool {
	if strings.HasPrefix(line, " ") || strings.HasPrefix(line, "\t") {
		return true
	}
	return listItem.MatchString(line)
}

var listItem = regexp.MustCompile(`^\s*([-*+]|[0-9]+[.)])\s`)

// isKindPackage keeps the comments of the API-group packages and drops everything else the walk
// picks up — the transport stubs, the storage contract, this module's own plumbing. The rule is
// the layout convention itself: a group package is one whose last path segment is its version
// (core/v1, rbac/v1). A group added later is included with no list to remember to update.
func isKindPackage(key string) bool {
	pkg, _, ok := strings.Cut(key[len(basePkg)+1:], ".")
	if !ok {
		return false
	}
	_, version, ok := strings.Cut(pkg, "/")
	return ok && versionSegment.MatchString(version)
}

// versionSegment matches a Kubernetes-style API version: v1, v2beta3.
var versionSegment = regexp.MustCompile(`^v[0-9]+((alpha|beta)[0-9]+)?$`)
