// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: netd.proto

// NetdService is the split-privilege seam: the unprivileged agent asks, the privileged
// helper (horchestra-netd) acts. It exists because the agent CANNOT act — creating a veth
// into the host's namespace needs CAP_NET_ADMIN there, and bpf() is gated on capabilities
// in the INITIAL user namespace (with kernel.unprivileged_bpf_disabled=2 even a map update
// needs CAP_BPF), and no user namespace grants either.
//
// THE INVARIANT: every method is closed and typed, carrying DATA. There is no ApplyNetlink,
// no Exec, and — the one that looks typed but is not — no LoadProgram. A BPF program is
// arbitrary kernel code; accepting one from the agent would hand root back through a
// typed-looking door. The helper loads what is embedded in its own binary; the agent says
// only WHAT it wants.
//
// The service is defined here rather than hand-rolled over a socket because the framing,
// deadlines, error transport, versioning and closed method set are exactly what an IDL
// gives — and a hand-written protocol re-earns each of them one bug at a time. What gRPC
// does NOT give is authentication: a unix peer is identified by SO_PEERCRED, which the
// helper checks in its transport credentials either way.

package netd

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetdService_Status_FullMethodName                  = "/horchestra.netd.v1.NetdService/Status"
	NetdService_SetupWorkloadNetwork_FullMethodName    = "/horchestra.netd.v1.NetdService/SetupWorkloadNetwork"
	NetdService_TeardownWorkloadNetwork_FullMethodName = "/horchestra.netd.v1.NetdService/TeardownWorkloadNetwork"
	NetdService_ProgramRoutes_FullMethodName           = "/horchestra.netd.v1.NetdService/ProgramRoutes"
	NetdService_ProgramServices_FullMethodName         = "/horchestra.netd.v1.NetdService/ProgramServices"
	NetdService_GC_FullMethodName                      = "/horchestra.netd.v1.NetdService/GC"
)

// NetdServiceClient is the client API for NetdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetdServiceClient interface {
	// Status is what this node can actually do, asked before anything is promised: an agent
	// that learns the workload network is unavailable keeps its workloads on the host network and
	// says so, instead of starting one isolated from everything including its control plane.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// SetupWorkloadNetwork wires the namespace a WORKLOAD already lives in: a veth pair with one end in it,
	// an address, and routes on both sides.
	//
	// Nobody hands a namespace to the workload, because the kernel does not allow it. setns into a
	// network namespace requires CAP_SYS_ADMIN in BOTH the user namespace that owns it and the
	// caller's CURRENT one — measured, not inferred: an unprivileged process cannot enter a
	// root-created namespace (EPERM) and cannot enter one owned by its own user's namespace either
	// (EPERM again). The one arrangement that works is the one where nothing has to enter: the
	// sandbox creates the network namespace inside the user namespace it has just unshared, so it
	// is already in it, and this helper — root, with CAP_SYS_ADMIN in an ancestor — reaches in to
	// wire it.
	//
	// Which is why the request names a PID and not a path. There is no pinned handle to keep, no
	// bind mount to place, and nothing to garbage-collect: the namespace lives exactly as long as
	// the workload in it.
	//
	// Idempotent: the host-side interface existing IS the record, so a repeat call re-applies the
	// addressing and returns — which matters because the agent converges the same workload on
	// every push.
	SetupWorkloadNetwork(ctx context.Context, in *SetupWorkloadNetworkRequest, opts ...grpc.CallOption) (*SetupWorkloadNetworkResponse, error)
	// TeardownWorkloadNetwork removes this helper's half: the veth pair. The namespace itself is the
	// agent's to reclaim, because it is the agent's to create.
	TeardownWorkloadNetwork(ctx context.Context, in *TeardownWorkloadNetworkRequest, opts ...grpc.CallOption) (*TeardownWorkloadNetworkResponse, error)
	// ProgramRoutes replaces the node's whole view of where workload addresses live. A REPLACE and
	// never a delta: a delta needs both sides to agree about what was applied before, which is
	// the second record this design refuses to keep.
	ProgramRoutes(ctx context.Context, in *ProgramRoutesRequest, opts ...grpc.CallOption) (*ProgramRoutesResponse, error)
	// ProgramServices replaces the datapath's (clusterIP, port) -> backends map, wholesale and
	// for the same reason.
	ProgramServices(ctx context.Context, in *ProgramServicesRequest, opts ...grpc.CallOption) (*ProgramServicesResponse, error)
	// GC reclaims every network the agent no longer names. The keep list is the whole
	// authority — the helper holds no opinion about what should exist, which is what stops it
	// from disagreeing with the control plane that does.
	GC(ctx context.Context, in *GCRequest, opts ...grpc.CallOption) (*GCResponse, error)
}

type netdServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetdServiceClient(cc grpc.ClientConnInterface) NetdServiceClient {
	return &netdServiceClient{cc}
}

func (c *netdServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NetdService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netdServiceClient) SetupWorkloadNetwork(ctx context.Context, in *SetupWorkloadNetworkRequest, opts ...grpc.CallOption) (*SetupWorkloadNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetupWorkloadNetworkResponse)
	err := c.cc.Invoke(ctx, NetdService_SetupWorkloadNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netdServiceClient) TeardownWorkloadNetwork(ctx context.Context, in *TeardownWorkloadNetworkRequest, opts ...grpc.CallOption) (*TeardownWorkloadNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TeardownWorkloadNetworkResponse)
	err := c.cc.Invoke(ctx, NetdService_TeardownWorkloadNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netdServiceClient) ProgramRoutes(ctx context.Context, in *ProgramRoutesRequest, opts ...grpc.CallOption) (*ProgramRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgramRoutesResponse)
	err := c.cc.Invoke(ctx, NetdService_ProgramRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netdServiceClient) ProgramServices(ctx context.Context, in *ProgramServicesRequest, opts ...grpc.CallOption) (*ProgramServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgramServicesResponse)
	err := c.cc.Invoke(ctx, NetdService_ProgramServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netdServiceClient) GC(ctx context.Context, in *GCRequest, opts ...grpc.CallOption) (*GCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GCResponse)
	err := c.cc.Invoke(ctx, NetdService_GC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetdServiceServer is the server API for NetdService service.
// All implementations must embed UnimplementedNetdServiceServer
// for forward compatibility.
type NetdServiceServer interface {
	// Status is what this node can actually do, asked before anything is promised: an agent
	// that learns the workload network is unavailable keeps its workloads on the host network and
	// says so, instead of starting one isolated from everything including its control plane.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// SetupWorkloadNetwork wires the namespace a WORKLOAD already lives in: a veth pair with one end in it,
	// an address, and routes on both sides.
	//
	// Nobody hands a namespace to the workload, because the kernel does not allow it. setns into a
	// network namespace requires CAP_SYS_ADMIN in BOTH the user namespace that owns it and the
	// caller's CURRENT one — measured, not inferred: an unprivileged process cannot enter a
	// root-created namespace (EPERM) and cannot enter one owned by its own user's namespace either
	// (EPERM again). The one arrangement that works is the one where nothing has to enter: the
	// sandbox creates the network namespace inside the user namespace it has just unshared, so it
	// is already in it, and this helper — root, with CAP_SYS_ADMIN in an ancestor — reaches in to
	// wire it.
	//
	// Which is why the request names a PID and not a path. There is no pinned handle to keep, no
	// bind mount to place, and nothing to garbage-collect: the namespace lives exactly as long as
	// the workload in it.
	//
	// Idempotent: the host-side interface existing IS the record, so a repeat call re-applies the
	// addressing and returns — which matters because the agent converges the same workload on
	// every push.
	SetupWorkloadNetwork(context.Context, *SetupWorkloadNetworkRequest) (*SetupWorkloadNetworkResponse, error)
	// TeardownWorkloadNetwork removes this helper's half: the veth pair. The namespace itself is the
	// agent's to reclaim, because it is the agent's to create.
	TeardownWorkloadNetwork(context.Context, *TeardownWorkloadNetworkRequest) (*TeardownWorkloadNetworkResponse, error)
	// ProgramRoutes replaces the node's whole view of where workload addresses live. A REPLACE and
	// never a delta: a delta needs both sides to agree about what was applied before, which is
	// the second record this design refuses to keep.
	ProgramRoutes(context.Context, *ProgramRoutesRequest) (*ProgramRoutesResponse, error)
	// ProgramServices replaces the datapath's (clusterIP, port) -> backends map, wholesale and
	// for the same reason.
	ProgramServices(context.Context, *ProgramServicesRequest) (*ProgramServicesResponse, error)
	// GC reclaims every network the agent no longer names. The keep list is the whole
	// authority — the helper holds no opinion about what should exist, which is what stops it
	// from disagreeing with the control plane that does.
	GC(context.Context, *GCRequest) (*GCResponse, error)
	mustEmbedUnimplementedNetdServiceServer()
}

// UnimplementedNetdServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetdServiceServer struct{}

func (UnimplementedNetdServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedNetdServiceServer) SetupWorkloadNetwork(context.Context, *SetupWorkloadNetworkRequest) (*SetupWorkloadNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetupWorkloadNetwork not implemented")
}
func (UnimplementedNetdServiceServer) TeardownWorkloadNetwork(context.Context, *TeardownWorkloadNetworkRequest) (*TeardownWorkloadNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TeardownWorkloadNetwork not implemented")
}
func (UnimplementedNetdServiceServer) ProgramRoutes(context.Context, *ProgramRoutesRequest) (*ProgramRoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProgramRoutes not implemented")
}
func (UnimplementedNetdServiceServer) ProgramServices(context.Context, *ProgramServicesRequest) (*ProgramServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProgramServices not implemented")
}
func (UnimplementedNetdServiceServer) GC(context.Context, *GCRequest) (*GCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GC not implemented")
}
func (UnimplementedNetdServiceServer) mustEmbedUnimplementedNetdServiceServer() {}
func (UnimplementedNetdServiceServer) testEmbeddedByValue()                     {}

// UnsafeNetdServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetdServiceServer will
// result in compilation errors.
type UnsafeNetdServiceServer interface {
	mustEmbedUnimplementedNetdServiceServer()
}

func RegisterNetdServiceServer(s grpc.ServiceRegistrar, srv NetdServiceServer) {
	// If the following call panics, it indicates UnimplementedNetdServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetdService_ServiceDesc, srv)
}

func _NetdService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetdServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetdService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetdServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetdService_SetupWorkloadNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupWorkloadNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetdServiceServer).SetupWorkloadNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetdService_SetupWorkloadNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetdServiceServer).SetupWorkloadNetwork(ctx, req.(*SetupWorkloadNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetdService_TeardownWorkloadNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeardownWorkloadNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetdServiceServer).TeardownWorkloadNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetdService_TeardownWorkloadNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetdServiceServer).TeardownWorkloadNetwork(ctx, req.(*TeardownWorkloadNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetdService_ProgramRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgramRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetdServiceServer).ProgramRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetdService_ProgramRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetdServiceServer).ProgramRoutes(ctx, req.(*ProgramRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetdService_ProgramServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgramServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetdServiceServer).ProgramServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetdService_ProgramServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetdServiceServer).ProgramServices(ctx, req.(*ProgramServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetdService_GC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetdServiceServer).GC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetdService_GC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetdServiceServer).GC(ctx, req.(*GCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NetdService_ServiceDesc is the grpc.ServiceDesc for NetdService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetdService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "horchestra.netd.v1.NetdService",
	HandlerType: (*NetdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _NetdService_Status_Handler,
		},
		{
			MethodName: "SetupWorkloadNetwork",
			Handler:    _NetdService_SetupWorkloadNetwork_Handler,
		},
		{
			MethodName: "TeardownWorkloadNetwork",
			Handler:    _NetdService_TeardownWorkloadNetwork_Handler,
		},
		{
			MethodName: "ProgramRoutes",
			Handler:    _NetdService_ProgramRoutes_Handler,
		},
		{
			MethodName: "ProgramServices",
			Handler:    _NetdService_ProgramServices_Handler,
		},
		{
			MethodName: "GC",
			Handler:    _NetdService_GC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "netd.proto",
}
