// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: netd.proto

// NetdService is the split-privilege seam: the unprivileged agent asks, the privileged
// helper (horchestra-netd) acts. It exists because the agent CANNOT act — creating a veth
// into the host's namespace needs CAP_NET_ADMIN there, and bpf() is gated on capabilities
// in the INITIAL user namespace (with kernel.unprivileged_bpf_disabled=2 even a map update
// needs CAP_BPF), and no user namespace grants either.
//
// THE INVARIANT: every method is closed and typed, carrying DATA. There is no ApplyNetlink,
// no Exec, and — the one that looks typed but is not — no LoadProgram. A BPF program is
// arbitrary kernel code; accepting one from the agent would hand root back through a
// typed-looking door. The helper loads what is embedded in its own binary; the agent says
// only WHAT it wants.
//
// The service is defined here rather than hand-rolled over a socket because the framing,
// deadlines, error transport, versioning and closed method set are exactly what an IDL
// gives — and a hand-written protocol re-earns each of them one bug at a time. What gRPC
// does NOT give is authentication: a unix peer is identified by SO_PEERCRED, which the
// helper checks in its transport credentials either way.

package netd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Workload identifies one workload's network. id is the Application's UID — the node's key for a
// workload everywhere else — so a delete-and-recreate under one name is two networks.
type Workload struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// address is the leased workload address in CIDR form (10.244.1.7/24), so the subnet needs no second
	// field that could disagree with it.
	Address string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	// gateway is the node-side address the namespace routes through.
	Gateway string `protobuf:"bytes,5,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// mtu leaves the kernel default at 0. An overlay costs ~50 bytes, and a workload that
	// learns that from a hanging TLS handshake learns it far too late.
	Mtu           int32 `protobuf:"varint,6,opt,name=mtu,proto3" json:"mtu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workload) Reset() {
	*x = Workload{}
	mi := &file_netd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workload) ProtoMessage() {}

func (x *Workload) ProtoReflect() protoreflect.Message {
	mi := &file_netd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workload.ProtoReflect.Descriptor instead.
func (*Workload) Descriptor() ([]byte, []int) {
	return file_netd_proto_rawDescGZIP(), []int{0}
}

func (x *Workload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workload) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Workload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workload) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Workload) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *Workload) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

// Route is where one node's workload addresses live: on this node (node_ip empty) or behind another's.
type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	NodeIp        string                 `protobuf:"bytes,2,opt,name=node_ip,json=nodeIp,proto3" json:"node_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_netd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_netd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_netd_proto_rawDescGZIP(), []int{1}
}

func (x *Route) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *Route) GetNodeIp() string {
	if x != nil {
		return x.NodeIp
	}
	return ""
}

// ServiceRule is one service the datapath answers for.
type ServiceRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterIp     string                 `protobuf:"bytes,1,opt,name=cluster_ip,json=clusterIp,proto3" json:"cluster_ip,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Backends      []*Backend             `protobuf:"bytes,4,rep,name=backends,proto3" json:"backends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRule) Reset() {
	*x = ServiceRule{}
	mi := &file_netd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRule) ProtoMessage() {}

func (x *ServiceRule) ProtoReflect() protoreflect.Message {
	mi := &file_netd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRule.ProtoReflect.Descriptor instead.
func (*ServiceRule) Descriptor() ([]byte, []int) {
	return file_netd_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceRule) GetClusterIp() string {
	if x != nil {
		return x.ClusterIp
	}
	return ""
}

func (x *ServiceRule) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServiceRule) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ServiceRule) GetBackends() []*Backend {
	if x != nil {
		return x.Backends
	}
	return nil
}

type Backend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backend) Reset() {
	*x = Backend{}
	mi := &file_netd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backend) ProtoMessage() {}

func (x *Backend) ProtoReflect() protoreflect.Message {
	mi := &file_netd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backend.ProtoReflect.Descriptor instead.
func (*Backend) Descriptor() ([]byte, []int) {
	return file_netd_proto_rawDescGZIP(), []int{3}
}

func (x *Backend) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Backend) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_netd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_netd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_netd_proto_rawDescGZIP(), []int{4}
}

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// version is the helper's build, for an operator staring at a mismatch.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// routed_network reports whether a namespace can be given an address and a route here —
	// the capability behind the sandbox's "routed" mode, and named after it because while there is
	// one mode they are one fact.
	RoutedNetwork bool `protobuf:"varint,2,opt,name=routed_network,json=routedNetwork,proto3" json:"routed_network,omitempty"`
	// datapath reports whether the eBPF programs are loaded and attached. Separate from
	// routed_network because a host may have namespaces and no BTF.
	Datapath bool `protobuf:"varint,3,opt,name=datapath,proto3" json:"datapath,omitempty"`
	// reason explains a false above, in the words an operator needs to fix it.
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_netd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_netd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_netd_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetRoutedNetwork() bool {
	if x != nil {
		return x.RoutedNetwork
	}
	return false
}

func (x *StatusResponse) GetDatapath() bool {
	if x != nil {
		return x.Datapath
	}
	return false
}

func (x *StatusResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SetupWorkloadNetworkRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Workload *Workload              `protobuf:"bytes,1,opt,name=workload,proto3" json:"workload,omitempty"`
	// netns_pid is a process living in the namespace to wire — the sandbox, waiting to exec the
	// workload. The helper reads /proc/<pid>/ns/net and checks that the process belongs to the
	// CALLER'S OWN uid, which it learns from the kernel (SO_PEERCRED) and not from this message:
	// an agent may wire the namespaces of its own workloads and of nothing else on the host.
	NetnsPid      int32 `protobuf:"varint,2,opt,name=netns_pid,json=netnsPid,proto3" json:"netns_pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupWorkloadNetworkRequest) Reset() {
	*x = SetupWorkloadNetworkRequest{}
	mi := &file_netd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupWorkloadNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupWorkloadNetworkRequest) ProtoMessage() {}

func (x *SetupWorkloadNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_netd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupWorkloadNetworkRequest.ProtoReflect.Descriptor instead.
func (*SetupWorkloadNetworkRequest) Descriptor() ([]byte, []int) {
	return file_netd_proto_rawDescGZIP(), []int{6}
}

func (x *SetupWorkloadNetworkRequest) GetWorkload() *Workload {
	if x != nil {
		return x.Workload
	}
	return nil
}

func (x *SetupWorkloadNetworkRequest) GetNetnsPid() int32 {
	if x != nil {
		return x.NetnsPid
	}
	return 0
}

type SetupWorkloadNetworkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host_interface is the node-side end of the pair, so an operator reading a node can find the
	// workload's link without recomputing a digest.
	HostInterface string `protobuf:"bytes,1,opt,name=host_interface,json=hostInterface,proto3" json:"host_interface,omitempty"`
	Address       string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupWorkloadNetworkResponse) Reset() {
	*x = SetupWorkloadNetworkResponse{}
	mi := &file_netd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupWorkloadNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupWorkloadNetworkResponse) ProtoMessage() {}

func (x *SetupWorkloadNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_netd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupWorkloadNetworkResponse.ProtoReflect.Descriptor instead.
func (*SetupWorkloadNetworkResponse) Descriptor() ([]byte, []int) {
	return file_netd_proto_rawDescGZIP(), []int{7}
}

func (x *SetupWorkloadNetworkResponse) GetHostInterface() string {
	if x != nil {
		return x.HostInterface
	}
	return ""
}

func (x *SetupWorkloadNetworkResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type TeardownWorkloadNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeardownWorkloadNetworkRequest) Reset() {
	*x = TeardownWorkloadNetworkRequest{}
	mi := &file_netd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeardownWorkloadNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeardownWorkloadNetworkRequest) ProtoMessage() {}

func (x *TeardownWorkloadNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_netd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeardownWorkloadNetworkRequest.ProtoReflect.Descriptor instead.
func (*TeardownWorkloadNetworkRequest) Descriptor() ([]byte, []int) {
	return file_netd_proto_rawDescGZIP(), []int{8}
}

func (x *TeardownWorkloadNetworkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TeardownWorkloadNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeardownWorkloadNetworkResponse) Reset() {
	*x = TeardownWorkloadNetworkResponse{}
	mi := &file_netd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeardownWorkloadNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeardownWorkloadNetworkResponse) ProtoMessage() {}

func (x *TeardownWorkloadNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_netd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeardownWorkloadNetworkResponse.ProtoReflect.Descriptor instead.
func (*TeardownWorkloadNetworkResponse) Descriptor() ([]byte, []int) {
	return file_netd_proto_rawDescGZIP(), []int{9}
}

type ProgramRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*Route               `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramRoutesRequest) Reset() {
	*x = ProgramRoutesRequest{}
	mi := &file_netd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramRoutesRequest) ProtoMessage() {}

func (x *ProgramRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_netd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramRoutesRequest.ProtoReflect.Descriptor instead.
func (*ProgramRoutesRequest) Descriptor() ([]byte, []int) {
	return file_netd_proto_rawDescGZIP(), []int{10}
}

func (x *ProgramRoutesRequest) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type ProgramRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramRoutesResponse) Reset() {
	*x = ProgramRoutesResponse{}
	mi := &file_netd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramRoutesResponse) ProtoMessage() {}

func (x *ProgramRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_netd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramRoutesResponse.ProtoReflect.Descriptor instead.
func (*ProgramRoutesResponse) Descriptor() ([]byte, []int) {
	return file_netd_proto_rawDescGZIP(), []int{11}
}

type ProgramServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceRule         `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramServicesRequest) Reset() {
	*x = ProgramServicesRequest{}
	mi := &file_netd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramServicesRequest) ProtoMessage() {}

func (x *ProgramServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_netd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramServicesRequest.ProtoReflect.Descriptor instead.
func (*ProgramServicesRequest) Descriptor() ([]byte, []int) {
	return file_netd_proto_rawDescGZIP(), []int{12}
}

func (x *ProgramServicesRequest) GetServices() []*ServiceRule {
	if x != nil {
		return x.Services
	}
	return nil
}

type ProgramServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramServicesResponse) Reset() {
	*x = ProgramServicesResponse{}
	mi := &file_netd_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramServicesResponse) ProtoMessage() {}

func (x *ProgramServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_netd_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramServicesResponse.ProtoReflect.Descriptor instead.
func (*ProgramServicesResponse) Descriptor() ([]byte, []int) {
	return file_netd_proto_rawDescGZIP(), []int{13}
}

type GCRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// keep is every workload id the agent still wants. An empty list is meaningful — the node
	// runs nothing — and is what makes GC total rather than a delta. What is reclaimed is this
	// helper's own state: the host-side interfaces of workloads no longer named. The namespaces
	// are the agent's and it reclaims them itself.
	Keep          []string `protobuf:"bytes,1,rep,name=keep,proto3" json:"keep,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GCRequest) Reset() {
	*x = GCRequest{}
	mi := &file_netd_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCRequest) ProtoMessage() {}

func (x *GCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_netd_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCRequest.ProtoReflect.Descriptor instead.
func (*GCRequest) Descriptor() ([]byte, []int) {
	return file_netd_proto_rawDescGZIP(), []int{14}
}

func (x *GCRequest) GetKeep() []string {
	if x != nil {
		return x.Keep
	}
	return nil
}

type GCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GCResponse) Reset() {
	*x = GCResponse{}
	mi := &file_netd_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCResponse) ProtoMessage() {}

func (x *GCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_netd_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCResponse.ProtoReflect.Descriptor instead.
func (*GCResponse) Descriptor() ([]byte, []int) {
	return file_netd_proto_rawDescGZIP(), []int{15}
}

var File_netd_proto protoreflect.FileDescriptor

const file_netd_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"netd.proto\x12\x12horchestra.netd.v1\"\x92\x01\n" +
	"\bWorkload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x18\n" +
	"\agateway\x18\x05 \x01(\tR\agateway\x12\x10\n" +
	"\x03mtu\x18\x06 \x01(\x05R\x03mtu\"4\n" +
	"\x05Route\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x12\x17\n" +
	"\anode_ip\x18\x02 \x01(\tR\x06nodeIp\"\x95\x01\n" +
	"\vServiceRule\x12\x1d\n" +
	"\n" +
	"cluster_ip\x18\x01 \x01(\tR\tclusterIp\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x127\n" +
	"\bbackends\x18\x04 \x03(\v2\x1b.horchestra.netd.v1.BackendR\bbackends\"7\n" +
	"\aBackend\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"\x0f\n" +
	"\rStatusRequest\"\x85\x01\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12%\n" +
	"\x0erouted_network\x18\x02 \x01(\bR\rroutedNetwork\x12\x1a\n" +
	"\bdatapath\x18\x03 \x01(\bR\bdatapath\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"t\n" +
	"\x1bSetupWorkloadNetworkRequest\x128\n" +
	"\bworkload\x18\x01 \x01(\v2\x1c.horchestra.netd.v1.WorkloadR\bworkload\x12\x1b\n" +
	"\tnetns_pid\x18\x02 \x01(\x05R\bnetnsPid\"_\n" +
	"\x1cSetupWorkloadNetworkResponse\x12%\n" +
	"\x0ehost_interface\x18\x01 \x01(\tR\rhostInterface\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"0\n" +
	"\x1eTeardownWorkloadNetworkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"!\n" +
	"\x1fTeardownWorkloadNetworkResponse\"I\n" +
	"\x14ProgramRoutesRequest\x121\n" +
	"\x06routes\x18\x01 \x03(\v2\x19.horchestra.netd.v1.RouteR\x06routes\"\x17\n" +
	"\x15ProgramRoutesResponse\"U\n" +
	"\x16ProgramServicesRequest\x12;\n" +
	"\bservices\x18\x01 \x03(\v2\x1f.horchestra.netd.v1.ServiceRuleR\bservices\"\x19\n" +
	"\x17ProgramServicesResponse\"\x1f\n" +
	"\tGCRequest\x12\x12\n" +
	"\x04keep\x18\x01 \x03(\tR\x04keep\"\f\n" +
	"\n" +
	"GCResponse2\xf5\x04\n" +
	"\vNetdService\x12O\n" +
	"\x06Status\x12!.horchestra.netd.v1.StatusRequest\x1a\".horchestra.netd.v1.StatusResponse\x12y\n" +
	"\x14SetupWorkloadNetwork\x12/.horchestra.netd.v1.SetupWorkloadNetworkRequest\x1a0.horchestra.netd.v1.SetupWorkloadNetworkResponse\x12\x82\x01\n" +
	"\x17TeardownWorkloadNetwork\x122.horchestra.netd.v1.TeardownWorkloadNetworkRequest\x1a3.horchestra.netd.v1.TeardownWorkloadNetworkResponse\x12d\n" +
	"\rProgramRoutes\x12(.horchestra.netd.v1.ProgramRoutesRequest\x1a).horchestra.netd.v1.ProgramRoutesResponse\x12j\n" +
	"\x0fProgramServices\x12*.horchestra.netd.v1.ProgramServicesRequest\x1a+.horchestra.netd.v1.ProgramServicesResponse\x12C\n" +
	"\x02GC\x12\x1d.horchestra.netd.v1.GCRequest\x1a\x1e.horchestra.netd.v1.GCResponseB-Z+github.com/ks-tool/horchestra/api/netd;netdb\x06proto3"

var (
	file_netd_proto_rawDescOnce sync.Once
	file_netd_proto_rawDescData []byte
)

func file_netd_proto_rawDescGZIP() []byte {
	file_netd_proto_rawDescOnce.Do(func() {
		file_netd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_netd_proto_rawDesc), len(file_netd_proto_rawDesc)))
	})
	return file_netd_proto_rawDescData
}

var file_netd_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_netd_proto_goTypes = []any{
	(*Workload)(nil),                        // 0: horchestra.netd.v1.Workload
	(*Route)(nil),                           // 1: horchestra.netd.v1.Route
	(*ServiceRule)(nil),                     // 2: horchestra.netd.v1.ServiceRule
	(*Backend)(nil),                         // 3: horchestra.netd.v1.Backend
	(*StatusRequest)(nil),                   // 4: horchestra.netd.v1.StatusRequest
	(*StatusResponse)(nil),                  // 5: horchestra.netd.v1.StatusResponse
	(*SetupWorkloadNetworkRequest)(nil),     // 6: horchestra.netd.v1.SetupWorkloadNetworkRequest
	(*SetupWorkloadNetworkResponse)(nil),    // 7: horchestra.netd.v1.SetupWorkloadNetworkResponse
	(*TeardownWorkloadNetworkRequest)(nil),  // 8: horchestra.netd.v1.TeardownWorkloadNetworkRequest
	(*TeardownWorkloadNetworkResponse)(nil), // 9: horchestra.netd.v1.TeardownWorkloadNetworkResponse
	(*ProgramRoutesRequest)(nil),            // 10: horchestra.netd.v1.ProgramRoutesRequest
	(*ProgramRoutesResponse)(nil),           // 11: horchestra.netd.v1.ProgramRoutesResponse
	(*ProgramServicesRequest)(nil),          // 12: horchestra.netd.v1.ProgramServicesRequest
	(*ProgramServicesResponse)(nil),         // 13: horchestra.netd.v1.ProgramServicesResponse
	(*GCRequest)(nil),                       // 14: horchestra.netd.v1.GCRequest
	(*GCResponse)(nil),                      // 15: horchestra.netd.v1.GCResponse
}
var file_netd_proto_depIdxs = []int32{
	3,  // 0: horchestra.netd.v1.ServiceRule.backends:type_name -> horchestra.netd.v1.Backend
	0,  // 1: horchestra.netd.v1.SetupWorkloadNetworkRequest.workload:type_name -> horchestra.netd.v1.Workload
	1,  // 2: horchestra.netd.v1.ProgramRoutesRequest.routes:type_name -> horchestra.netd.v1.Route
	2,  // 3: horchestra.netd.v1.ProgramServicesRequest.services:type_name -> horchestra.netd.v1.ServiceRule
	4,  // 4: horchestra.netd.v1.NetdService.Status:input_type -> horchestra.netd.v1.StatusRequest
	6,  // 5: horchestra.netd.v1.NetdService.SetupWorkloadNetwork:input_type -> horchestra.netd.v1.SetupWorkloadNetworkRequest
	8,  // 6: horchestra.netd.v1.NetdService.TeardownWorkloadNetwork:input_type -> horchestra.netd.v1.TeardownWorkloadNetworkRequest
	10, // 7: horchestra.netd.v1.NetdService.ProgramRoutes:input_type -> horchestra.netd.v1.ProgramRoutesRequest
	12, // 8: horchestra.netd.v1.NetdService.ProgramServices:input_type -> horchestra.netd.v1.ProgramServicesRequest
	14, // 9: horchestra.netd.v1.NetdService.GC:input_type -> horchestra.netd.v1.GCRequest
	5,  // 10: horchestra.netd.v1.NetdService.Status:output_type -> horchestra.netd.v1.StatusResponse
	7,  // 11: horchestra.netd.v1.NetdService.SetupWorkloadNetwork:output_type -> horchestra.netd.v1.SetupWorkloadNetworkResponse
	9,  // 12: horchestra.netd.v1.NetdService.TeardownWorkloadNetwork:output_type -> horchestra.netd.v1.TeardownWorkloadNetworkResponse
	11, // 13: horchestra.netd.v1.NetdService.ProgramRoutes:output_type -> horchestra.netd.v1.ProgramRoutesResponse
	13, // 14: horchestra.netd.v1.NetdService.ProgramServices:output_type -> horchestra.netd.v1.ProgramServicesResponse
	15, // 15: horchestra.netd.v1.NetdService.GC:output_type -> horchestra.netd.v1.GCResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_netd_proto_init() }
func file_netd_proto_init() {
	if File_netd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_netd_proto_rawDesc), len(file_netd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_netd_proto_goTypes,
		DependencyIndexes: file_netd_proto_depIdxs,
		MessageInfos:      file_netd_proto_msgTypes,
	}.Build()
	File_netd_proto = out.File
	file_netd_proto_goTypes = nil
	file_netd_proto_depIdxs = nil
}
