// Command gensyscalls regenerates syscalls.go, the syscall name tables the
// seccomp filter resolves a custom policy against, so a policy can name a
// syscall instead of numbering it. Numbers are per-ABI, which is why one table
// per architecture exists at all.
//
// The source is x/sys/unix's generated tables, which the sandbox already
// depends on. Run it from the repository root after bumping that dependency:
//
//	go run ./hack/gensyscalls
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

// out is the generated file, in the sandbox's own package.
const out = "syscalls.go"

// arches maps the architectures the seccomp filter supports to their table
// variable; an architecture the filter cannot build a program for has no use
// for a name table.
var arches = []struct{ goarch, variable string }{
	{"amd64", "syscallsAMD64"},
	{"arm64", "syscallsARM64"},
}

var sysConst = regexp.MustCompile(`^\tSYS_([A-Z0-9_]+)\s+=\s+(\d+)$`)

func main() {
	log.SetFlags(0)
	log.SetPrefix("gensyscalls: ")

	dir, err := unixPackageDir()
	if err != nil {
		log.Fatal(err)
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by hack/gensyscalls. DO NOT EDIT.\n\n//go:build linux\n\npackage sandbox\n")
	for _, a := range arches {
		entries, err := table(filepath.Join(dir, "zsysnum_linux_"+a.goarch+".go"))
		if err != nil {
			log.Fatal(err)
		}
		// Numeric order, as the ABI lists them: a kernel adding a syscall then
		// appends to the end instead of stirring the whole table.
		fmt.Fprintf(&b, "\n// %s maps a syscall name to its number on %s.\nvar %s = map[string]uint32{\n",
			a.variable, a.goarch, a.variable)
		max := 0
		for _, e := range entries {
			fmt.Fprintf(&b, "\t%q: %s,\n", e.name, e.number)
			if n, err := strconv.Atoi(e.number); err == nil && n > max {
				max = n
			}
		}
		b.WriteString("}\n")
		// The ceiling the filter denies above: a syscall this table has never heard of is one
		// the kernel grew after it was generated, and the denylist cannot have an opinion on it.
		fmt.Fprintf(&b, "\n// %sMax is the highest syscall number in the table above.\nconst %sMax uint32 = %d\n",
			a.variable, a.variable, max)
		fmt.Printf("%s: %d syscalls\n", a.goarch, len(entries))
	}

	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatalf("formatting %s: %v", out, err)
	}
	if err := os.WriteFile(out, src, 0o644); err != nil {
		log.Fatal(err)
	}
}

// unixPackageDir locates the x/sys/unix source in the module cache.
func unixPackageDir() (string, error) {
	cmd, err := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", "golang.org/x/sys").Output()
	if err != nil {
		return "", fmt.Errorf("locating golang.org/x/sys: %w", err)
	}
	return filepath.Join(strings.TrimSpace(string(cmd)), "unix"), nil
}

type entry struct{ name, number string }

// table reads one zsysnum file and returns its syscalls in the file's own
// (numeric) order.
func table(path string) ([]entry, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer func() { _ = f.Close() }()

	var entries []entry
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		if m := sysConst.FindStringSubmatch(sc.Text()); m != nil {
			entries = append(entries, entry{strings.ToLower(m[1]), m[2]})
		}
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	if len(entries) == 0 {
		return nil, fmt.Errorf("%s: no syscall constants found", path)
	}
	return entries, nil
}
