// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: node.proto

package node

import (
	netd "github.com/ks-tool/horchestra/api/netd"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*NodeMessage_Status
	//	*NodeMessage_LogChunk
	//	*NodeMessage_AppStatus
	//	*NodeMessage_AppMetrics
	//	*NodeMessage_NodeUsage
	Body          isNodeMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *NodeMessage) GetBody() isNodeMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *NodeMessage) GetStatus() *NodeStatus {
	if x != nil {
		if x, ok := x.Body.(*NodeMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *NodeMessage) GetLogChunk() *LogChunk {
	if x != nil {
		if x, ok := x.Body.(*NodeMessage_LogChunk); ok {
			return x.LogChunk
		}
	}
	return nil
}

func (x *NodeMessage) GetAppStatus() *AppStatus {
	if x != nil {
		if x, ok := x.Body.(*NodeMessage_AppStatus); ok {
			return x.AppStatus
		}
	}
	return nil
}

func (x *NodeMessage) GetAppMetrics() *AppMetrics {
	if x != nil {
		if x, ok := x.Body.(*NodeMessage_AppMetrics); ok {
			return x.AppMetrics
		}
	}
	return nil
}

func (x *NodeMessage) GetNodeUsage() *NodeUsage {
	if x != nil {
		if x, ok := x.Body.(*NodeMessage_NodeUsage); ok {
			return x.NodeUsage
		}
	}
	return nil
}

type isNodeMessage_Body interface {
	isNodeMessage_Body()
}

type NodeMessage_Status struct {
	Status *NodeStatus `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

type NodeMessage_LogChunk struct {
	LogChunk *LogChunk `protobuf:"bytes,2,opt,name=log_chunk,json=logChunk,proto3,oneof"`
}

type NodeMessage_AppStatus struct {
	AppStatus *AppStatus `protobuf:"bytes,3,opt,name=app_status,json=appStatus,proto3,oneof"`
}

type NodeMessage_AppMetrics struct {
	AppMetrics *AppMetrics `protobuf:"bytes,4,opt,name=app_metrics,json=appMetrics,proto3,oneof"`
}

type NodeMessage_NodeUsage struct {
	NodeUsage *NodeUsage `protobuf:"bytes,5,opt,name=node_usage,json=nodeUsage,proto3,oneof"`
}

func (*NodeMessage_Status) isNodeMessage_Body() {}

func (*NodeMessage_LogChunk) isNodeMessage_Body() {}

func (*NodeMessage_AppStatus) isNodeMessage_Body() {}

func (*NodeMessage_AppMetrics) isNodeMessage_Body() {}

func (*NodeMessage_NodeUsage) isNodeMessage_Body() {}

// NodeUsage is what the MACHINE is consuming, as distinct from the sum of its workloads —
// which would miss the system, the agent itself and everything else on the host, and so would
// be the wrong number to compare a capacity against.
//
// Read from /proc, not from cgroup arithmetic: the whole node is what `kubectl top node`
// means, and /proc/stat and /proc/meminfo are the kernel's own answer to it and readable by
// anyone. Like AppMetrics it is held in memory and never stored.
type NodeUsage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cumulative busy CPU time across all cores, so the reader derives a rate over the window
	// it wants — the same rule the per-workload counters follow.
	CpuUsec           int64 `protobuf:"varint,1,opt,name=cpu_usec,json=cpuUsec,proto3" json:"cpu_usec,omitempty"`
	MemoryUsedBytes   int64 `protobuf:"varint,2,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes  int64 `protobuf:"varint,3,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	TimestampUnixNano int64 `protobuf:"varint,4,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeUsage) Reset() {
	*x = NodeUsage{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeUsage) ProtoMessage() {}

func (x *NodeUsage) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeUsage.ProtoReflect.Descriptor instead.
func (*NodeUsage) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *NodeUsage) GetCpuUsec() int64 {
	if x != nil {
		return x.CpuUsec
	}
	return 0
}

func (x *NodeUsage) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *NodeUsage) GetMemoryTotalBytes() int64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *NodeUsage) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

// AppMetrics is what one workload actually consumed, read from its cgroup by the node and
// reported on the heartbeat.
//
// It is NOT part of AppStatus, deliberately. Status is the state of an object and is stored;
// these are a sample of a moving quantity, and writing them into storage every heartbeat
// would churn an object's resourceVersion forever, wake every watcher of the Kind, and still
// leave no history worth having. They are held in the controller's memory, exactly as
// metrics-server does, and are gone when it restarts.
type AppMetrics struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Namespace string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Cumulative since the workload started. A rate is the reader's job — sending one would
	// bake this node's sampling interval into the number.
	CpuUsec int64 `protobuf:"varint,3,opt,name=cpu_usec,json=cpuUsec,proto3" json:"cpu_usec,omitempty"`
	// How long the cgroup was throttled by its CPU quota: the number that says a limit is
	// biting, which usage alone never shows.
	CpuThrottledUsec int64 `protobuf:"varint,4,opt,name=cpu_throttled_usec,json=cpuThrottledUsec,proto3" json:"cpu_throttled_usec,omitempty"`
	MemoryBytes      int64 `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	// The high-water mark since start — what a request should have been, which current usage
	// cannot tell you.
	MemoryPeakBytes int64 `protobuf:"varint,6,opt,name=memory_peak_bytes,json=memoryPeakBytes,proto3" json:"memory_peak_bytes,omitempty"`
	Pids            int64 `protobuf:"varint,7,opt,name=pids,proto3" json:"pids,omitempty"`
	// The kernel's own count. A workload that was OOM-killed and restarted looks healthy
	// afterwards; this is the only thing that remembers.
	OomKills          int64 `protobuf:"varint,8,opt,name=oom_kills,json=oomKills,proto3" json:"oom_kills,omitempty"`
	TimestampUnixNano int64 `protobuf:"varint,9,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AppMetrics) Reset() {
	*x = AppMetrics{}
	mi := &file_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppMetrics) ProtoMessage() {}

func (x *AppMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppMetrics.ProtoReflect.Descriptor instead.
func (*AppMetrics) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

func (x *AppMetrics) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AppMetrics) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppMetrics) GetCpuUsec() int64 {
	if x != nil {
		return x.CpuUsec
	}
	return 0
}

func (x *AppMetrics) GetCpuThrottledUsec() int64 {
	if x != nil {
		return x.CpuThrottledUsec
	}
	return 0
}

func (x *AppMetrics) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *AppMetrics) GetMemoryPeakBytes() int64 {
	if x != nil {
		return x.MemoryPeakBytes
	}
	return 0
}

func (x *AppMetrics) GetPids() int64 {
	if x != nil {
		return x.Pids
	}
	return 0
}

func (x *AppMetrics) GetOomKills() int64 {
	if x != nil {
		return x.OomKills
	}
	return 0
}

func (x *AppMetrics) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

// AppStatus is the node-observed runtime status of one Application pinned to this
// node — its phase (Running/Failed/Pending) and an optional message. The controller
// persists it to the Application's status subresource, confined to apps on this node.
// It carries only what the node OBSERVED: the supervisor unit's name is derived from
// the workload's uid by whichever runtime supervises it, so reporting it would put a
// node-side naming rule on the wire and into the API for no reader.
type AppStatus struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Namespace string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phase     string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	Message   string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// The metadata.generation of the Application this node actually converged to. It NAMES
	// the version the node is running, which phase alone cannot: a node that fails to apply
	// a new spec keeps the previous workload running and would otherwise look healthy on the
	// new one. A rollout gates on it.
	ObservedGeneration int64 `protobuf:"varint,6,opt,name=observed_generation,json=observedGeneration,proto3" json:"observed_generation,omitempty"`
	// How a finished workload finished. A phase alone says a job ended; these say whether it
	// ended the way it was meant to and when, which is the whole reason to look at a job after
	// it stops. Both are zero while the workload is still running.
	ExitCode           int32 `protobuf:"varint,7,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	FinishedAtUnixNano int64 `protobuf:"varint,8,opt,name=finished_at_unix_nano,json=finishedAtUnixNano,proto3" json:"finished_at_unix_nano,omitempty"`
	// The routed address this node WIRED the workload at, empty on the host network. It travels
	// up because the node is what observed it — the same arrangement Kubernetes has for podIP —
	// and because the control plane reads its own past choices back off these reports: the choice
	// rides down in the push and is durable only once a node says it is so.
	Address string `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	// How many times this node has run the job, spent against spec.lifecycle.backoffLimit. It
	// travels up because the count has to outlive the unit that holds it: a transient unit dies
	// with the node's manager, so a node-local counter would hand every job a fresh budget after
	// a reboot. Zero for a service, whose restarts are systemd's and are not budgeted.
	Attempts      int32 `protobuf:"varint,9,opt,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppStatus) Reset() {
	*x = AppStatus{}
	mi := &file_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppStatus) ProtoMessage() {}

func (x *AppStatus) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppStatus.ProtoReflect.Descriptor instead.
func (*AppStatus) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{3}
}

func (x *AppStatus) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AppStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *AppStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AppStatus) GetObservedGeneration() int64 {
	if x != nil {
		return x.ObservedGeneration
	}
	return 0
}

func (x *AppStatus) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *AppStatus) GetFinishedAtUnixNano() int64 {
	if x != nil {
		return x.FinishedAtUnixNano
	}
	return 0
}

func (x *AppStatus) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AppStatus) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

// NodeStatus carries the full Node object (metadata + status) as JSON, reusing
// the api/v1 serialization instead of re-modelling it in protobuf.
type NodeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          []byte                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{4}
}

func (x *NodeStatus) GetNode() []byte {
	if x != nil {
		return x.Node
	}
	return nil
}

// LogChunk is a slice of an application's log output, correlated to a LogRequest
// by id. eof marks the end of the stream; error is set if the node could not read
// the logs.
type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,3,opt,name=eof,proto3" json:"eof,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{5}
}

func (x *LogChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

func (x *LogChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ControllerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ControllerMessage_Desired
	//	*ControllerMessage_LogRequest
	//	*ControllerMessage_LogCancel
	Body          isControllerMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerMessage) Reset() {
	*x = ControllerMessage{}
	mi := &file_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage) ProtoMessage() {}

func (x *ControllerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage.ProtoReflect.Descriptor instead.
func (*ControllerMessage) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{6}
}

func (x *ControllerMessage) GetBody() isControllerMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ControllerMessage) GetDesired() *DesiredState {
	if x != nil {
		if x, ok := x.Body.(*ControllerMessage_Desired); ok {
			return x.Desired
		}
	}
	return nil
}

func (x *ControllerMessage) GetLogRequest() *LogRequest {
	if x != nil {
		if x, ok := x.Body.(*ControllerMessage_LogRequest); ok {
			return x.LogRequest
		}
	}
	return nil
}

func (x *ControllerMessage) GetLogCancel() *LogCancel {
	if x != nil {
		if x, ok := x.Body.(*ControllerMessage_LogCancel); ok {
			return x.LogCancel
		}
	}
	return nil
}

type isControllerMessage_Body interface {
	isControllerMessage_Body()
}

type ControllerMessage_Desired struct {
	Desired *DesiredState `protobuf:"bytes,1,opt,name=desired,proto3,oneof"`
}

type ControllerMessage_LogRequest struct {
	LogRequest *LogRequest `protobuf:"bytes,2,opt,name=log_request,json=logRequest,proto3,oneof"`
}

type ControllerMessage_LogCancel struct {
	LogCancel *LogCancel `protobuf:"bytes,3,opt,name=log_cancel,json=logCancel,proto3,oneof"`
}

func (*ControllerMessage_Desired) isControllerMessage_Body() {}

func (*ControllerMessage_LogRequest) isControllerMessage_Body() {}

func (*ControllerMessage_LogCancel) isControllerMessage_Body() {}

// DesiredState is the set the node must reconcile: every Application and
// PersistentVolume, plus the Secrets its pinned apps reference and the
// SecretStores those secrets name (connection info only — a vault secret's
// value never transits this stream), each a JSON api object (the node filters
// to itself, the way it did when it listed them over REST).
type DesiredState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Applications      [][]byte               `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	PersistentVolumes [][]byte               `protobuf:"bytes,2,rep,name=persistent_volumes,json=persistentVolumes,proto3" json:"persistent_volumes,omitempty"`
	Secrets           [][]byte               `protobuf:"bytes,3,rep,name=secrets,proto3" json:"secrets,omitempty"`
	SecretStores      [][]byte               `protobuf:"bytes,4,rep,name=secret_stores,json=secretStores,proto3" json:"secret_stores,omitempty"`
	// Short-lived controller-minted workload-identity JWTs, one per pinned app that
	// references a jwt-method SecretStore: the node exchanges the token at Vault's jwt
	// auth method for exactly that workload's read. The controller is the credential
	// issuer here, never a value carrier.
	WorkloadTokens []*WorkloadToken `protobuf:"bytes,5,rep,name=workload_tokens,json=workloadTokens,proto3" json:"workload_tokens,omitempty"`
	// The routed address each isolated workload is to be wired at. Delivered rather than stored on
	// the Application for the reason a token is: it is a per-workload decision of the control
	// plane, and a workload's object is its author's manifest. The node wires it and reports the
	// result in the Application's status, which is what makes the choice durable — the control
	// plane reads its own past decisions back off what the nodes observed.
	WorkloadNetworks []*WorkloadNetwork `protobuf:"bytes,6,rep,name=workload_networks,json=workloadNetworks,proto3" json:"workload_networks,omitempty"`
	// Where every workload address in the FLEET lives, and what every ClusterIP balances onto. Both
	// are the node's whole view, replaced on each push and never a delta.
	//
	// This is where the least-exposure rule that scopes applications, volumes and secrets to one node
	// necessarily stops, and it stops for a reason and not by oversight: a datapath that answers a
	// ClusterIP has to know its backends, and one that forwards a flat address range has to know
	// where each address is. Scoping either to "what this node runs" would leave a node unable to
	// reach half the cluster — the packets come from any process on the host, not only from the
	// workloads the node was told about.
	Routes        []*netd.Route       `protobuf:"bytes,7,rep,name=routes,proto3" json:"routes,omitempty"`
	Services      []*netd.ServiceRule `protobuf:"bytes,8,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DesiredState) Reset() {
	*x = DesiredState{}
	mi := &file_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredState) ProtoMessage() {}

func (x *DesiredState) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredState.ProtoReflect.Descriptor instead.
func (*DesiredState) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{7}
}

func (x *DesiredState) GetApplications() [][]byte {
	if x != nil {
		return x.Applications
	}
	return nil
}

func (x *DesiredState) GetPersistentVolumes() [][]byte {
	if x != nil {
		return x.PersistentVolumes
	}
	return nil
}

func (x *DesiredState) GetSecrets() [][]byte {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *DesiredState) GetSecretStores() [][]byte {
	if x != nil {
		return x.SecretStores
	}
	return nil
}

func (x *DesiredState) GetWorkloadTokens() []*WorkloadToken {
	if x != nil {
		return x.WorkloadTokens
	}
	return nil
}

func (x *DesiredState) GetWorkloadNetworks() []*WorkloadNetwork {
	if x != nil {
		return x.WorkloadNetworks
	}
	return nil
}

func (x *DesiredState) GetRoutes() []*netd.Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *DesiredState) GetServices() []*netd.ServiceRule {
	if x != nil {
		return x.Services
	}
	return nil
}

// WorkloadNetwork is one workload's routed address and the gateway it routes through.
type WorkloadNetwork struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// workload is the object UID, the node's key for a workload everywhere else.
	Workload string `protobuf:"bytes,1,opt,name=workload,proto3" json:"workload,omitempty"`
	// address is in CIDR form (10.244.1.7/32): each workload is its own point-to-point link, so
	// there is no subnet on the wire for a broader prefix to describe.
	Address       string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Gateway       string `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Mtu           int32  `protobuf:"varint,4,opt,name=mtu,proto3" json:"mtu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadNetwork) Reset() {
	*x = WorkloadNetwork{}
	mi := &file_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadNetwork) ProtoMessage() {}

func (x *WorkloadNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadNetwork.ProtoReflect.Descriptor instead.
func (*WorkloadNetwork) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{8}
}

func (x *WorkloadNetwork) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

func (x *WorkloadNetwork) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WorkloadNetwork) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *WorkloadNetwork) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

// WorkloadToken pairs a workload with one of its identity JWTs. There is one per
// (workload, audience): a token minted for Vault is a login at Vault and nothing at
// the control plane, and the one a workload reads the catalog with is the reverse —
// which is what keeps a single stolen credential worth one door.
type WorkloadToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workload      string                 `protobuf:"bytes,1,opt,name=workload,proto3" json:"workload,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Audience      string                 `protobuf:"bytes,3,opt,name=audience,proto3" json:"audience,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadToken) Reset() {
	*x = WorkloadToken{}
	mi := &file_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadToken) ProtoMessage() {}

func (x *WorkloadToken) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadToken.ProtoReflect.Descriptor instead.
func (*WorkloadToken) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{9}
}

func (x *WorkloadToken) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

func (x *WorkloadToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *WorkloadToken) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

// LogRequest asks the node to stream one application's unit logs back up as
// LogChunks tagged with id. tail_lines caps the initial backlog (0 = all).
type LogRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	App       string                 `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	Follow    bool                   `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`
	TailLines int64                  `protobuf:"varint,4,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	// NodeUnit asks for the AGENT'S OWN unit journal instead of a workload's. It is a separate
	// field rather than a reserved value in `app` on purpose: a sentinel in the field that
	// otherwise names a workload reads as a bug six months later, and the one thing this must
	// never do is resolve to a workload by accident.
	//
	// It is the agent's unit and not the host journal. The host journal carries the output of
	// every workload on the node, so serving it here would hand over in one call what
	// pods/log serves one workload at a time with a permission check on each.
	NodeUnit      bool `protobuf:"varint,5,opt,name=node_unit,json=nodeUnit,proto3" json:"node_unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{10}
}

func (x *LogRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *LogRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogRequest) GetTailLines() int64 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *LogRequest) GetNodeUnit() bool {
	if x != nil {
		return x.NodeUnit
	}
	return false
}

// LogCancel stops an in-progress LogRequest (e.g. the client disconnected).
type LogCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogCancel) Reset() {
	*x = LogCancel{}
	mi := &file_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogCancel) ProtoMessage() {}

func (x *LogCancel) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogCancel.ProtoReflect.Descriptor instead.
func (*LogCancel) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{11}
}

func (x *LogCancel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x12\x12horchestra.node.v1\x1a\n" +
	"netd.proto\"\xcf\x02\n" +
	"\vNodeMessage\x128\n" +
	"\x06status\x18\x01 \x01(\v2\x1e.horchestra.node.v1.NodeStatusH\x00R\x06status\x12;\n" +
	"\tlog_chunk\x18\x02 \x01(\v2\x1c.horchestra.node.v1.LogChunkH\x00R\blogChunk\x12>\n" +
	"\n" +
	"app_status\x18\x03 \x01(\v2\x1d.horchestra.node.v1.AppStatusH\x00R\tappStatus\x12A\n" +
	"\vapp_metrics\x18\x04 \x01(\v2\x1e.horchestra.node.v1.AppMetricsH\x00R\n" +
	"appMetrics\x12>\n" +
	"\n" +
	"node_usage\x18\x05 \x01(\v2\x1d.horchestra.node.v1.NodeUsageH\x00R\tnodeUsageB\x06\n" +
	"\x04body\"\xb0\x01\n" +
	"\tNodeUsage\x12\x19\n" +
	"\bcpu_usec\x18\x01 \x01(\x03R\acpuUsec\x12*\n" +
	"\x11memory_used_bytes\x18\x02 \x01(\x03R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x03 \x01(\x03R\x10memoryTotalBytes\x12.\n" +
	"\x13timestamp_unix_nano\x18\x04 \x01(\x03R\x11timestampUnixNano\"\xb7\x02\n" +
	"\n" +
	"AppMetrics\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bcpu_usec\x18\x03 \x01(\x03R\acpuUsec\x12,\n" +
	"\x12cpu_throttled_usec\x18\x04 \x01(\x03R\x10cpuThrottledUsec\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x03R\vmemoryBytes\x12*\n" +
	"\x11memory_peak_bytes\x18\x06 \x01(\x03R\x0fmemoryPeakBytes\x12\x12\n" +
	"\x04pids\x18\a \x01(\x03R\x04pids\x12\x1b\n" +
	"\toom_kills\x18\b \x01(\x03R\boomKills\x12.\n" +
	"\x13timestamp_unix_nano\x18\t \x01(\x03R\x11timestampUnixNano\"\xa4\x02\n" +
	"\tAppStatus\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12/\n" +
	"\x13observed_generation\x18\x06 \x01(\x03R\x12observedGeneration\x12\x1b\n" +
	"\texit_code\x18\a \x01(\x05R\bexitCode\x121\n" +
	"\x15finished_at_unix_nano\x18\b \x01(\x03R\x12finishedAtUnixNano\x12\x18\n" +
	"\aaddress\x18\n" +
	" \x01(\tR\aaddress\x12\x1a\n" +
	"\battempts\x18\t \x01(\x05R\battempts\" \n" +
	"\n" +
	"NodeStatus\x12\x12\n" +
	"\x04node\x18\x01 \x01(\fR\x04node\"V\n" +
	"\bLogChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eof\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xdc\x01\n" +
	"\x11ControllerMessage\x12<\n" +
	"\adesired\x18\x01 \x01(\v2 .horchestra.node.v1.DesiredStateH\x00R\adesired\x12A\n" +
	"\vlog_request\x18\x02 \x01(\v2\x1e.horchestra.node.v1.LogRequestH\x00R\n" +
	"logRequest\x12>\n" +
	"\n" +
	"log_cancel\x18\x03 \x01(\v2\x1d.horchestra.node.v1.LogCancelH\x00R\tlogCancelB\x06\n" +
	"\x04body\"\xae\x03\n" +
	"\fDesiredState\x12\"\n" +
	"\fapplications\x18\x01 \x03(\fR\fapplications\x12-\n" +
	"\x12persistent_volumes\x18\x02 \x03(\fR\x11persistentVolumes\x12\x18\n" +
	"\asecrets\x18\x03 \x03(\fR\asecrets\x12#\n" +
	"\rsecret_stores\x18\x04 \x03(\fR\fsecretStores\x12J\n" +
	"\x0fworkload_tokens\x18\x05 \x03(\v2!.horchestra.node.v1.WorkloadTokenR\x0eworkloadTokens\x12P\n" +
	"\x11workload_networks\x18\x06 \x03(\v2#.horchestra.node.v1.WorkloadNetworkR\x10workloadNetworks\x121\n" +
	"\x06routes\x18\a \x03(\v2\x19.horchestra.netd.v1.RouteR\x06routes\x12;\n" +
	"\bservices\x18\b \x03(\v2\x1f.horchestra.netd.v1.ServiceRuleR\bservices\"s\n" +
	"\x0fWorkloadNetwork\x12\x1a\n" +
	"\bworkload\x18\x01 \x01(\tR\bworkload\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x18\n" +
	"\agateway\x18\x03 \x01(\tR\agateway\x12\x10\n" +
	"\x03mtu\x18\x04 \x01(\x05R\x03mtu\"]\n" +
	"\rWorkloadToken\x12\x1a\n" +
	"\bworkload\x18\x01 \x01(\tR\bworkload\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1a\n" +
	"\baudience\x18\x03 \x01(\tR\baudience\"\x82\x01\n" +
	"\n" +
	"LogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03app\x18\x02 \x01(\tR\x03app\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x04 \x01(\x03R\ttailLines\x12\x1b\n" +
	"\tnode_unit\x18\x05 \x01(\bR\bnodeUnit\"\x1b\n" +
	"\tLogCancel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2d\n" +
	"\vNodeService\x12U\n" +
	"\aSession\x12\x1f.horchestra.node.v1.NodeMessage\x1a%.horchestra.node.v1.ControllerMessage(\x010\x01B-Z+github.com/ks-tool/horchestra/api/node;nodeb\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_node_proto_goTypes = []any{
	(*NodeMessage)(nil),       // 0: horchestra.node.v1.NodeMessage
	(*NodeUsage)(nil),         // 1: horchestra.node.v1.NodeUsage
	(*AppMetrics)(nil),        // 2: horchestra.node.v1.AppMetrics
	(*AppStatus)(nil),         // 3: horchestra.node.v1.AppStatus
	(*NodeStatus)(nil),        // 4: horchestra.node.v1.NodeStatus
	(*LogChunk)(nil),          // 5: horchestra.node.v1.LogChunk
	(*ControllerMessage)(nil), // 6: horchestra.node.v1.ControllerMessage
	(*DesiredState)(nil),      // 7: horchestra.node.v1.DesiredState
	(*WorkloadNetwork)(nil),   // 8: horchestra.node.v1.WorkloadNetwork
	(*WorkloadToken)(nil),     // 9: horchestra.node.v1.WorkloadToken
	(*LogRequest)(nil),        // 10: horchestra.node.v1.LogRequest
	(*LogCancel)(nil),         // 11: horchestra.node.v1.LogCancel
	(*netd.Route)(nil),        // 12: horchestra.netd.v1.Route
	(*netd.ServiceRule)(nil),  // 13: horchestra.netd.v1.ServiceRule
}
var file_node_proto_depIdxs = []int32{
	4,  // 0: horchestra.node.v1.NodeMessage.status:type_name -> horchestra.node.v1.NodeStatus
	5,  // 1: horchestra.node.v1.NodeMessage.log_chunk:type_name -> horchestra.node.v1.LogChunk
	3,  // 2: horchestra.node.v1.NodeMessage.app_status:type_name -> horchestra.node.v1.AppStatus
	2,  // 3: horchestra.node.v1.NodeMessage.app_metrics:type_name -> horchestra.node.v1.AppMetrics
	1,  // 4: horchestra.node.v1.NodeMessage.node_usage:type_name -> horchestra.node.v1.NodeUsage
	7,  // 5: horchestra.node.v1.ControllerMessage.desired:type_name -> horchestra.node.v1.DesiredState
	10, // 6: horchestra.node.v1.ControllerMessage.log_request:type_name -> horchestra.node.v1.LogRequest
	11, // 7: horchestra.node.v1.ControllerMessage.log_cancel:type_name -> horchestra.node.v1.LogCancel
	9,  // 8: horchestra.node.v1.DesiredState.workload_tokens:type_name -> horchestra.node.v1.WorkloadToken
	8,  // 9: horchestra.node.v1.DesiredState.workload_networks:type_name -> horchestra.node.v1.WorkloadNetwork
	12, // 10: horchestra.node.v1.DesiredState.routes:type_name -> horchestra.netd.v1.Route
	13, // 11: horchestra.node.v1.DesiredState.services:type_name -> horchestra.netd.v1.ServiceRule
	0,  // 12: horchestra.node.v1.NodeService.Session:input_type -> horchestra.node.v1.NodeMessage
	6,  // 13: horchestra.node.v1.NodeService.Session:output_type -> horchestra.node.v1.ControllerMessage
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	file_node_proto_msgTypes[0].OneofWrappers = []any{
		(*NodeMessage_Status)(nil),
		(*NodeMessage_LogChunk)(nil),
		(*NodeMessage_AppStatus)(nil),
		(*NodeMessage_AppMetrics)(nil),
		(*NodeMessage_NodeUsage)(nil),
	}
	file_node_proto_msgTypes[6].OneofWrappers = []any{
		(*ControllerMessage_Desired)(nil),
		(*ControllerMessage_LogRequest)(nil),
		(*ControllerMessage_LogCancel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
