// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: node.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*NodeMessage_Status
	//	*NodeMessage_LogChunk
	Body          isNodeMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *NodeMessage) GetBody() isNodeMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *NodeMessage) GetStatus() *NodeStatus {
	if x != nil {
		if x, ok := x.Body.(*NodeMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *NodeMessage) GetLogChunk() *LogChunk {
	if x != nil {
		if x, ok := x.Body.(*NodeMessage_LogChunk); ok {
			return x.LogChunk
		}
	}
	return nil
}

type isNodeMessage_Body interface {
	isNodeMessage_Body()
}

type NodeMessage_Status struct {
	Status *NodeStatus `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

type NodeMessage_LogChunk struct {
	LogChunk *LogChunk `protobuf:"bytes,2,opt,name=log_chunk,json=logChunk,proto3,oneof"`
}

func (*NodeMessage_Status) isNodeMessage_Body() {}

func (*NodeMessage_LogChunk) isNodeMessage_Body() {}

// NodeStatus carries the full Node object (metadata + status) as JSON, reusing
// the api/v1 serialization instead of re-modelling it in protobuf.
type NodeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          []byte                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *NodeStatus) GetNode() []byte {
	if x != nil {
		return x.Node
	}
	return nil
}

// LogChunk is a slice of an application's log output, correlated to a LogRequest
// by id. eof marks the end of the stream; error is set if the node could not read
// the logs.
type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,3,opt,name=eof,proto3" json:"eof,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

func (x *LogChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

func (x *LogChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ControllerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ControllerMessage_Desired
	//	*ControllerMessage_LogRequest
	//	*ControllerMessage_LogCancel
	Body          isControllerMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerMessage) Reset() {
	*x = ControllerMessage{}
	mi := &file_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage) ProtoMessage() {}

func (x *ControllerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage.ProtoReflect.Descriptor instead.
func (*ControllerMessage) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{3}
}

func (x *ControllerMessage) GetBody() isControllerMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ControllerMessage) GetDesired() *DesiredState {
	if x != nil {
		if x, ok := x.Body.(*ControllerMessage_Desired); ok {
			return x.Desired
		}
	}
	return nil
}

func (x *ControllerMessage) GetLogRequest() *LogRequest {
	if x != nil {
		if x, ok := x.Body.(*ControllerMessage_LogRequest); ok {
			return x.LogRequest
		}
	}
	return nil
}

func (x *ControllerMessage) GetLogCancel() *LogCancel {
	if x != nil {
		if x, ok := x.Body.(*ControllerMessage_LogCancel); ok {
			return x.LogCancel
		}
	}
	return nil
}

type isControllerMessage_Body interface {
	isControllerMessage_Body()
}

type ControllerMessage_Desired struct {
	Desired *DesiredState `protobuf:"bytes,1,opt,name=desired,proto3,oneof"`
}

type ControllerMessage_LogRequest struct {
	LogRequest *LogRequest `protobuf:"bytes,2,opt,name=log_request,json=logRequest,proto3,oneof"`
}

type ControllerMessage_LogCancel struct {
	LogCancel *LogCancel `protobuf:"bytes,3,opt,name=log_cancel,json=logCancel,proto3,oneof"`
}

func (*ControllerMessage_Desired) isControllerMessage_Body() {}

func (*ControllerMessage_LogRequest) isControllerMessage_Body() {}

func (*ControllerMessage_LogCancel) isControllerMessage_Body() {}

// DesiredState is the set the node must reconcile: every Application and
// PersistentVolume, each a JSON api/v1 object (the node filters to itself, the
// way it did when it listed them over REST).
type DesiredState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Applications      [][]byte               `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	PersistentVolumes [][]byte               `protobuf:"bytes,2,rep,name=persistent_volumes,json=persistentVolumes,proto3" json:"persistent_volumes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DesiredState) Reset() {
	*x = DesiredState{}
	mi := &file_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredState) ProtoMessage() {}

func (x *DesiredState) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredState.ProtoReflect.Descriptor instead.
func (*DesiredState) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{4}
}

func (x *DesiredState) GetApplications() [][]byte {
	if x != nil {
		return x.Applications
	}
	return nil
}

func (x *DesiredState) GetPersistentVolumes() [][]byte {
	if x != nil {
		return x.PersistentVolumes
	}
	return nil
}

// LogRequest asks the node to stream one application's unit logs back up as
// LogChunks tagged with id. tail_lines caps the initial backlog (0 = all).
type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	App           string                 `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	Follow        bool                   `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`
	TailLines     int64                  `protobuf:"varint,4,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{5}
}

func (x *LogRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *LogRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogRequest) GetTailLines() int64 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

// LogCancel stops an in-progress LogRequest (e.g. the client disconnected).
type LogCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogCancel) Reset() {
	*x = LogCancel{}
	mi := &file_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogCancel) ProtoMessage() {}

func (x *LogCancel) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogCancel.ProtoReflect.Descriptor instead.
func (*LogCancel) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{6}
}

func (x *LogCancel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x12\x12horchestra.node.v1\"\x8c\x01\n" +
	"\vNodeMessage\x128\n" +
	"\x06status\x18\x01 \x01(\v2\x1e.horchestra.node.v1.NodeStatusH\x00R\x06status\x12;\n" +
	"\tlog_chunk\x18\x02 \x01(\v2\x1c.horchestra.node.v1.LogChunkH\x00R\blogChunkB\x06\n" +
	"\x04body\" \n" +
	"\n" +
	"NodeStatus\x12\x12\n" +
	"\x04node\x18\x01 \x01(\fR\x04node\"V\n" +
	"\bLogChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eof\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xdc\x01\n" +
	"\x11ControllerMessage\x12<\n" +
	"\adesired\x18\x01 \x01(\v2 .horchestra.node.v1.DesiredStateH\x00R\adesired\x12A\n" +
	"\vlog_request\x18\x02 \x01(\v2\x1e.horchestra.node.v1.LogRequestH\x00R\n" +
	"logRequest\x12>\n" +
	"\n" +
	"log_cancel\x18\x03 \x01(\v2\x1d.horchestra.node.v1.LogCancelH\x00R\tlogCancelB\x06\n" +
	"\x04body\"a\n" +
	"\fDesiredState\x12\"\n" +
	"\fapplications\x18\x01 \x03(\fR\fapplications\x12-\n" +
	"\x12persistent_volumes\x18\x02 \x03(\fR\x11persistentVolumes\"e\n" +
	"\n" +
	"LogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03app\x18\x02 \x01(\tR\x03app\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x04 \x01(\x03R\ttailLines\"\x1b\n" +
	"\tLogCancel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2d\n" +
	"\vNodeService\x12U\n" +
	"\aSession\x12\x1f.horchestra.node.v1.NodeMessage\x1a%.horchestra.node.v1.ControllerMessage(\x010\x01B)Z'github.com/ks-tool/horchestra/api/pb;pbb\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_node_proto_goTypes = []any{
	(*NodeMessage)(nil),       // 0: horchestra.node.v1.NodeMessage
	(*NodeStatus)(nil),        // 1: horchestra.node.v1.NodeStatus
	(*LogChunk)(nil),          // 2: horchestra.node.v1.LogChunk
	(*ControllerMessage)(nil), // 3: horchestra.node.v1.ControllerMessage
	(*DesiredState)(nil),      // 4: horchestra.node.v1.DesiredState
	(*LogRequest)(nil),        // 5: horchestra.node.v1.LogRequest
	(*LogCancel)(nil),         // 6: horchestra.node.v1.LogCancel
}
var file_node_proto_depIdxs = []int32{
	1, // 0: horchestra.node.v1.NodeMessage.status:type_name -> horchestra.node.v1.NodeStatus
	2, // 1: horchestra.node.v1.NodeMessage.log_chunk:type_name -> horchestra.node.v1.LogChunk
	4, // 2: horchestra.node.v1.ControllerMessage.desired:type_name -> horchestra.node.v1.DesiredState
	5, // 3: horchestra.node.v1.ControllerMessage.log_request:type_name -> horchestra.node.v1.LogRequest
	6, // 4: horchestra.node.v1.ControllerMessage.log_cancel:type_name -> horchestra.node.v1.LogCancel
	0, // 5: horchestra.node.v1.NodeService.Session:input_type -> horchestra.node.v1.NodeMessage
	3, // 6: horchestra.node.v1.NodeService.Session:output_type -> horchestra.node.v1.ControllerMessage
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	file_node_proto_msgTypes[0].OneofWrappers = []any{
		(*NodeMessage_Status)(nil),
		(*NodeMessage_LogChunk)(nil),
	}
	file_node_proto_msgTypes[3].OneofWrappers = []any{
		(*ControllerMessage_Desired)(nil),
		(*ControllerMessage_LogRequest)(nil),
		(*ControllerMessage_LogCancel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
